cli.py: The mode/action argument is required
The mode/action argument is required for reasonable behavior, so tell
argparse that.

Before:
```
$ docker-pkg
Traceback (most recent call last):
  File "/home/dancy/.pyenv/versions/integration-config/bin/docker-pkg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dancy/src/wmf/operations/docker-images/docker-pkg/docker_pkg/cli.py", line 179, in main
    select = args.select
             ^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'select'
```

This is unpleasant and unhelpful for users.

After:
```
$ docker-pkg
usage: docker-pkg [-h] [-c CONFIGFILE] [--debug | --info] {build,prune,update} ...
docker-pkg: error: the following arguments are required: mode
```

Change-Id: I1198230395c3dfa7785d12ef0ad94c7f3c76b1ed