cli.py: Improve UX when config file does not exist
Before:
```
$ docker-pkg build .
Traceback (most recent call last):
  File "/home/dancy/.pyenv/versions/integration-config/bin/docker-pkg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dancy/src/wmf/operations/docker-images/docker-pkg/docker_pkg/cli.py", line 172, in main
    config = read_config(args.configfile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dancy/src/wmf/operations/docker-images/docker-pkg/docker_pkg/cli.py", line 146, in read_config
    local_config = _read_config_file(configfile)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dancy/src/wmf/operations/docker-images/docker-pkg/docker_pkg/cli.py", line 130, in _read_config_file
    with open(configfile, "rb") as fh:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

```

After:
```
$ docker-pkg build .
Config file config.yaml does not exist
```

Change-Id: I7bd51e5e23b3c30273a2066223c320acf747e263