tox: pin mypy<1.16.0
mypy 1.16.0 causes a new failure:

docker_pkg/builder.py:123: error: Argument "proxies" to "get" has
incompatible type "dict[str, Optional[Any]]"; expected
"Optional[MutableMapping[str, str]]"  [arg-type]

Pin the version until that is resolved.

Change-Id: I47902f40a3aa4e430d85f5278c199bea838ba9de